#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    # colorscheme = "nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    statusline_iseparator = "fire"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    bootstrap_after = "my_configs#after"
    filemanager = 'nerdtree'   
    # checking tools
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true




# enable other colorscheme
[[layers]]
  name = 'colorscheme'

# checkers to show highlights in statusbar instead
[[layers]]
  name = 'checkers'
  show_cursor_error = false

# vim-fugitive layer
[[layers]]
  name = 'VersionControl'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lang#python"
  format_on_save = 1

[[layers]]
  name = "tmux"

[[layers]]
  name = "denite"

##################################################
# Custom plugins
##################################################

[[custom_plugins]]
  repo = "tpope/vim-fugitive"
  merge = false

[[custom_plugins]]
  repo = "christoomey/vim-tmux-navigator"
  merged = false


[[custom_plugins]]
  repo = "chriskempson/base16-vim"
  merged = false


